services:
  - type: web
    name: social-media-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn social_media_analyzer.wsgi:application
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: analyzer-db
          property: connectionString

databases:
  - name: analyzer-db
    plan: free
